---
- name: apt cache
  apt: update_cache=yes

- name: Install common packages
  apt: pkg={{ item }} state=latest
  with_items:
    - sudo
    - vim
    - htop
    - iftop
    - iotop
    - git
    - mercurial
    - tortoisehg
    - build-essential
    - curl
    - wget
    - spfquery
    - mc
    - nodejs
    - nodejs-legacy
    - npm
    - php5-cli
    - mysql-client-core-5.6

# - include: foobar.yml
