---

- name: Add optipng-ppa key
  apt_key: keyserver=keyserver.ubuntu.com id=D117DE3E
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

- name: Add optipng/stable-ppa repository
  apt_repository: repo='ppa:optipng/stable'
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
  register: optpng_repository

- name: Add tortoisehg-ppa key
  apt_key: keyserver=keyserver.ubuntu.com id=D5056DDE
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

- name: Add tortoisehg-ppa repository
  apt_repository: repo='ppa:tortoisehg-ppa/releases'
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
  register: tortoisehg_repository

- name: apt-get update
  apt: update_cache=yes
  when: optpng_repository.changed or tortoisehg_repository.changed
  
- name: Install optipng
  apt: pkg=optipng state=latest
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

- name: Install common packages
  apt: pkg={{ item }} state=latest
  with_items:
    - sudo
    - vim
    - htop
    - iftop
    - iotop
    - git
    - mercurial
    - tortoisehg
    - build-essential
    - curl
    - wget
    - spfquery
    - mc
    - nodejs
    - nodejs-legacy
    - npm
    - php5-cli
    - php5-mcrypt
    - php5-memcache
    - php5-memcached
    - php5-imagick
    - php5-xhprof
    - php5-tidy
    - php5-intl
    - php5-gd
    - php5-curl
    - php5-mysql
    - mutt
    - filezilla

- name: Install common packages (Ubuntu trusty)
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-client-core-5.6
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

- name: Install common packages (Debian)
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-client
  when: ansible_distribution == 'Debian'


- name: Install uglify
  npm: name=uglify global=yes

- name: Install uglify-js
  npm: name=uglify-js global=yes

- name: Install svgo
  npm: name=svgo global=yes
