---

- name: Add tortoisehg-ppa key
  apt_key: keyserver=keyserver.ubuntu.com id=D5056DDE

- name: Add tortoisehg-ppa repository
  apt_repository: repo='ppa:tortoisehg-ppa/releases'

- name: apt cache
  apt: update_cache=yes

- name: Install common packages
  apt: pkg={{ item }} state=latest
  with_items:
    - sudo
    - vim
    - htop
    - iftop
    - iotop
    - git
    - mercurial
    - tortoisehg
    - build-essential
    - curl
    - wget
    - spfquery
    - mc
    - nodejs
    - nodejs-legacy
    - npm
    - php5-cli
    - php5-mcrypt
    - php5-memcache
    - php5-memcached
    - php5-imagick
    - php5-xhprof
    - php5-tidy
    - php5-intl
    - php5-gd
    - php5-curl
    - php5-mysql
    - mysql-client-core-5.6
    - mutt
    - filezilla

- name: Install uglify
  npm: name=uglify global=yes

- name: Install uglify-js
  npm: name=uglify-js global=yes