---
- name: Projects directory
  file: path={{ devhome | mandatory }}/projects state=directory owner={{ devuser | mandatory }} group={{ devuser | mandatory }} mode=0750

- name: Projects vhosts directory
  file: path={{ devhome | mandatory }}/projects/vhosts state=directory owner={{ devuser | mandatory }} group={{ devuser | mandatory }} mode=0750

- name: Projects log directory
  file: path={{ devhome | mandatory }}/projects/log state=directory owner={{ devuser | mandatory }} group={{ devuser | mandatory }} mode=0750

- name: Projects mail directory
  file: path={{ devhome | mandatory }}/projects/mail state=directory owner={{ devuser | mandatory }} group={{ devuser | mandatory }} mode=0750

- name: Docker directory
  file: path={{ devhome | mandatory }}/docker/projects-php state=directory owner={{ devuser | mandatory }} group={{ devuser | mandatory }} mode=0750

- name: Docker php directory
  file: path={{ devhome | mandatory }}/docker/projects-php/php state=directory owner={{ devuser | mandatory }} group={{ devuser | mandatory }} mode=0750

- stat: path={{ devhome | mandatory }}/projects/vhosts/php-projects.ini
  register: phpprojectsini

- name: Copy php-projects.ini php
  template: "src=php/php-projects.ini.j2 dest={{ devhome | mandatory }}/projects/vhosts/php-projects.ini mode=0640 owner={{ devuser | mandatory }} group={{ devuser | mandatory }}"
  when:  not phpprojectsini.stat.exists

- name: Copy msmtprc
  template: "src=php/msmtprc.j2 dest={{ devhome | mandatory }}/docker/projects-php/php/msmtprc mode=0640 owner={{ devuser | mandatory }} group={{ devuser | mandatory }}"

- name: Copy dockerfile php
  template: "src=php/Dockerfile.j2 dest={{ devhome | mandatory }}/docker/projects-php/php/Dockerfile mode=0640 owner={{ devuser | mandatory }} group={{ devuser | mandatory }}"

- name: Copy apache conf
  template: "src=php/projects-php.conf.j2 dest={{ devhome | mandatory }}/docker/projects-php/php/default.conf mode=0640 owner={{ devuser | mandatory }} group={{ devuser | mandatory }}"

- name: Docker mysql directory
  file: path={{ devhome | mandatory }}/docker/projects-php/mysql state=directory owner={{ devuser | mandatory }} group={{ devuser | mandatory }} mode=0750

- name: Copy dockerfile mysql
  template: "src=mysql/Dockerfile.j2 dest={{ devhome | mandatory }}/docker/projects-php/mysql/Dockerfile mode=0640 owner={{ devuser | mandatory }} group={{ devuser | mandatory }}"

- name: Copy entrypoint mysql
  template: "src=mysql/docker-entrypoint.sh.j2 dest={{ devhome | mandatory }}/docker/projects-php/mysql/docker-entrypoint.sh mode=0740 owner={{ devuser | mandatory }} group={{ devuser | mandatory }}"

- name: mysql data directory
  file: path={{ devhome | mandatory }}/projects/mysql/data state=directory owner={{ devuser | mandatory }} group={{ devuser | mandatory }} mode=0750

- name: Docker mail directory
  file: path={{ devhome | mandatory }}/docker/projects-php/mail state=directory owner={{ devuser | mandatory }} group={{ devuser | mandatory }} mode=0750
  
- name: Copy dockerfile mail
  template: "src=mail/Dockerfile.j2 dest={{ devhome | mandatory }}/docker/projects-php/mail/Dockerfile mode=0640 owner={{ devuser | mandatory }} group={{ devuser | mandatory }}"

- name: Docker elasticsearch directory
  file: path={{ devhome | mandatory }}/docker/projects-php/elasticsearch/data state=directory owner={{ devuser | mandatory }} group={{ devuser | mandatory }} mode=0750
  
- name: add nginx site
  template: src=projects-php.nginx.j2 dest=/etc/nginx/sites-available/projects-php-base mode=0644
  when: proxy == "nginx"

- name: symlink nginx devsystem site
  file: src=/etc/nginx/sites-available/projects-php-base dest=/etc/nginx/sites-enabled/projects-php-base owner=root group=root state=link
  notify:
    - nginx-restart
  when: proxy == "nginx"

- name: docker-compose.yml
  template: "src=docker-compose.yml.j2 dest={{ devhome | mandatory }}/docker/projects-php/docker-compose.yml mode=0640 owner={{ devuser | mandatory }} group={{ devuser | mandatory }}"

- name: vhost template
  template: "src=vhost.tmpl.j2 dest={{ devhome | mandatory }}/projects/vhosts/vhost.tmpl mode=0640 owner={{ devuser | mandatory }} group={{ devuser | mandatory }}"

- name: vhost add script
  template: "src=projects-php-vhost-add.sh.j2 dest={{ devhome | mandatory }}/bin/projects-php-vhost-add mode=0700 owner={{ devuser | mandatory }} group={{ devuser | mandatory }}"

- name: database add script
  template: "src=projects-php-database-add.sh.j2 dest={{ devhome | mandatory }}/bin/projects-php-database-add mode=0700 owner={{ devuser | mandatory }} group={{ devuser | mandatory }}"

- name: mysql client script
  template: "src=projects-php-mysql.sh.j2 dest={{ devhome | mandatory }}/bin/projects-php-mysql mode=0700 owner={{ devuser | mandatory }} group={{ devuser | mandatory }}"

- name: docker-compose script
  template: "src=projects-php-docker-compose.sh.j2 dest={{ devhome | mandatory }}/bin/projects-php-docker-compose mode=0700 owner={{ devuser | mandatory }} group={{ devuser | mandatory }}"

- name: exec script
  template: "src=projects-php-exec.sh.j2 dest={{ devhome | mandatory }}/bin/projects-php-exec mode=0700 owner={{ devuser | mandatory }} group={{ devuser | mandatory }}"

- name: mutt script
  template: "src=projects-php-mutt.sh.j2 dest={{ devhome | mandatory }}/bin/projects-php-mutt mode=0700 owner={{ devuser | mandatory }} group={{ devuser | mandatory }}"
