FROM debian:jessie
MAINTAINER Martin Schnabel <mcnilz@gmail.com>

RUN groupadd -r {{ devuser | mandatory }} -g {{ devgid | mandatory }} && \
	useradd -u {{ devuid | mandatory }} -r -g {{ devuser | mandatory }} -d {{ devhome | mandatory }} -s /bin/bash -c "Docker image user" {{ devuser | mandatory }} && \
	mkdir -p {{ devhome | mandatory }} && \
	chown -R {{ devuser | mandatory }}:{{ devuser | mandatory }} {{ devhome | mandatory }}

ENV REFRESH_FORCE 2015-04-01

RUN apt-get update && \
	apt-get -y upgrade && \
	DEBIAN_FRONTEND=noninteractive apt-get -y install postfix postfix-pcre mutt rsyslog

RUN echo "/.*/ {{ devuser | mandatory }}" > /etc/postfix/virtual && \
	sed -i "s,mynetworks =.*,mynetworks = 127.0.0.0/8 172.17.0.0/16 [::ffff:127.0.0.0]/104 [::1]/128," /etc/postfix/main.cf && \
	echo "virtual_alias_maps = pcre:/etc/postfix/virtual" >> /etc/postfix/main.cf && \
	touch /var/log/mail.log

EXPOSE 25

CMD ["sh", "-c", "service rsyslog start ; service postfix start ; tail -F /var/log/mail.log"]
