FROM ubuntu:trusty
MAINTAINER Martin Schnabel <mcnilz@gmail.com>
 
RUN apt-get update
# RUN apt-get -y upgrade

RUN DEBIAN_FRONTEND=noninteractive apt-get -y install apache2 libapache2-mod-php5 php5-mysql php5-gd php-pear php-apc php5-curl \
 curl lynx-cur php5-mcrypt php5-memcache php5-memcached php5-imagick php5-xhprof php5-tidy php5-intl
RUN a2enmod php5
RUN a2enmod rewrite
RUN php5enmod mcrypt
RUN sed -i "s/short_open_tag = Off/short_open_tag = On/" /etc/php5/apache2/php.ini
RUN sed -i "s/error_reporting = .*$/error_reporting = E_ERROR | E_WARNING | E_PARSE/" /etc/php5/apache2/php.ini

RUN groupadd -r {{ devuser | mandatory }} -g {{ devgid | mandatory }} && \
    useradd -u {{ devuid | mandatory }} -r -g {{ devuser | mandatory }} -d {{ devhome | mandatory }} -s /bin/bash -c "Docker image user" {{ devuser | mandatory }} && \
    mkdir -p {{ devhome | mandatory }} && \
    chown -R {{ devuser | mandatory }}:{{ devuser | mandatory }} {{ devhome | mandatory }} && \
    chown -R {{ devuser | mandatory }}:{{ devuser | mandatory }} /var/log/apache2 /var/lock/apache2

RUN sed -i "s/export APACHE_RUN_USER=www-data/export APACHE_RUN_USER={{ devuser | mandatory }}/" /etc/apache2/envvars
RUN sed -i "s/export APACHE_RUN_GROUP=www-data/export APACHE_RUN_GROUP={{ devuser | mandatory }}/" /etc/apache2/envvars

RUN cd /etc/php5/apache2/conf.d && ln -s {{ devhome | mandatory }}/projects/vhosts/php-projects.ini php-projects.ini

RUN locale-gen de_DE && locale-gen de_DE.UTF-8 && locale-gen en_US && locale-gen en_US.UTF-8 && locale-gen en_GB && locale-gen en_GB.UTF-8 && \
    locale-gen fr_FR && locale-gen fr_FR.UTF-8 && locale-gen it_IT && locale-gen it_IT.UTF-8 && update-locale

EXPOSE 80

ADD default.conf /etc/apache2/sites-enabled/000-default.conf

CMD /usr/sbin/apache2ctl -D FOREGROUND
