---

# TODO: https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/virtualbox-ppa when ubuntu kernel > 3.13

#- name: apt cache
#  apt: update_cache=yes

- name: Install Virtualbox Guest
  apt: pkg={{ item }} state=latest
  with_items:
    - virtualbox-guest-dkms
    - virtualbox-guest-utils
    - virtualbox-guest-x11
