---
- name: apt-transport-https
  apt: pkg=apt-transport-https state=installed

- name: docker key
  apt_key: keyserver=p80.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D

- name: docker repo (jessie)
  apt_repository: repo="deb https://apt.dockerproject.org/repo debian-jessie main" state=present
  register: docker_repository
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie'

- name: docker repo (trusty)
  apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-trusty main" state=present
  register: docker_repository
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

- name: apt-get update
  apt: update_cache=yes
  when: docker_repository.changed

- name: remove old docker
  apt: pkg=lxc-docker state=absent

- name: install docker
  apt: pkg=docker-engine state=latest

- name: add user to docker group
  user: "name={{ devuser | mandatory }} groups=docker append=yes"

#- name: install python pip
#  apt: pkg=python-pip state=latest
#  when: ansible_distribution == 'Ubuntu'

#- name: docker-compose
#  pip: name=docker-compose state=absent

- name: create user bin directory
  shell: "mkdir -p {{ devhome | mandatory }}/bin"
  args:
    creates: "{{ devhome | mandatory }}/bin"

- name: user bin owner
  file: "path={{ devhome | mandatory }}/bin"
  args:
    owner: "{{ devuser | mandatory }}"
    group: "{{ devuser | mandatory }}"

- name: install docker-compose 1.6.0
  shell: "curl -L https://github.com/docker/compose/releases/download/1.6.0/docker-compose-`uname -s`-`uname -m` > {{ devhome | mandatory }}/bin/docker-compose-1.6.0"
  args:
    creates: "{{ devhome | mandatory }}/bin/docker-compose-1.6.0"

- name: docker-compose owner
  file: "path={{ devhome | mandatory }}/bin/docker-compose-1.6.0"
  args:
    owner: "{{ devuser | mandatory }}"
    group: "{{ devuser | mandatory }}"
    mode: "u+x"

- name: docker-compose symlink
  file: "src=docker-compose-1.6.0 dest={{ devhome | mandatory }}/bin/docker-compose owner={{ devuser | mandatory }} group={{ devuser | mandatory }} state=link"

- name: install docker-maschine 0.6.0
  shell: "curl -L https://github.com/docker/machine/releases/download/v0.6.0/docker-machine-`uname -s`-`uname -m` > {{ devhome | mandatory }}/bin/docker-machine-0.6.0"
  args:
    creates: "{{ devhome | mandatory }}/bin/docker-machine-0.6.0"

- name: docker-machine owner
  file: "path={{ devhome | mandatory }}/bin/docker-machine-0.6.0"
  args:
    owner: "{{ devuser | mandatory }}"
    group: "{{ devuser | mandatory }}"
    mode: "u+x"

- name: docker-machine symlink
  file: "src=docker-machine-0.6.0 dest={{ devhome | mandatory }}/bin/docker-machine owner={{ devuser | mandatory }} group={{ devuser | mandatory }} state=link"
