---
- name: Developer system
  hosts: local
  sudo: yes
  roles:
    - { role: virtualbox-guest, when: virtualbox_guest_enabled }
    - { role: samba,            when: samba_enabled }
    - tools
    - grunt
    - bower
    - composer
    - javaoracle
    - docker
    - nginx
    - docker-projects-php
