---
- name: Developer system
  hosts: local
  sudo: yes
  roles:
    - { role: virtualbox-guest,   when: virtualbox_guest_enabled }
    - { role: samba,              when: samba_enabled }
    - tools
    - grunt
    - bower
    - composer
    - javaoracle
    - docker
    - { role: nginx,              when: proxy == "nginx" }
    - { role: docker-nginx-proxy, when: proxy == "docker-nginx-proxy" }
    - docker-projects-php
