---
- name: Developer System in Virtualbox
  hosts: local
  sudo: yes
  roles:
    - virtualbox-guest
    - samba
    - tools
    - grunt
    - bower
    - composer
    - javaoracle
    - docker
    - nginx
    - docker-projects-php