---
- name: Developer system
  hosts: local
  sudo: yes
  roles:
    - { role: user,                when: user_enabled }
    - { role: virtualbox-guest,    when: virtualbox_guest_enabled }
    - { role: samba,               when: samba_enabled }
    - { role: nodejs,              when: nodejs_enabled } 
    - { role: tools,               when: tools_enabled }
    - { role: composer,            when: composer_enabled }
    - { role: javaoracle,          when: java }
    - { role: docker }
    - { role: nginx,               when: proxy == "nginx" }
    - { role: docker-nginx-proxy,  when: proxy == "docker-nginx-proxy" }
    - { role: docker-projects-php, when: projects_php_enabled }
