---
- name: create user bin directory
  shell: "mkdir -p {{ devhome | mandatory }}/bin"
  args:
    creates: "{{ devhome | mandatory }}/bin"

- name: user bin owner
  file: "path={{ devhome | mandatory }}/bin"
  args:
    owner: "{{ devuser | mandatory }}"
    group: "{{ devuser | mandatory }}"

- name: install composer
  shell: "curl -sS https://getcomposer.org/installer | php -- --install-dir={{ devhome | mandatory }}/bin"
  args:
    creates: "{{ devhome | mandatory }}/bin/composer.phar"

- name: composer owner
  file: "path={{ devhome | mandatory }}/bin/composer.phar"
  args:
    owner: "{{ devuser | mandatory }}"
    group: "{{ devuser | mandatory }}"

- name: composer symlink
  file: "src=composer.phar dest={{ devhome | mandatory }}/bin/composer owner={{ devuser | mandatory }} group={{ devuser | mandatory }} state=link"